### ISSUE TITLE
Album Description textedit field is missing/hidden

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/ZenPhoto20#552]
I'm using the 1.3.4.0 build and finding that on the admin pages where I would edit an Album's name etc., the text entry field for the album description seems to be hidden.  My existing Album Descriptions are all there when I view the gallery but the ability to edit these descriptions or add new ones seems to be lost.  I don't know when this happened, it's been a while since I have done any album editing work.  In admin mode, no descriptions appear and there's no text edit box visible.

**Comment by sbillard** [comment]
This is most likely a Javascript error or incompatibility. You can verify this by disabling the tinyMCE plugin. If the fields then show up we will need to figure out what is preventing tinyMCE from running properly. I am not able to reproduce the issue on my server.  TinyMCE was updated to 4,4,3 as part of the 1.3.4 release, but I have not heard of any issues with it. There is a newer version that we might try though.

You can check things like the Apache access log to see if anything did not load. Also maybe the Java error logs in your browser.

**Comment by nerdykit** [comment]
I can confirm that turning off tinyMCE restores the Album Description field.  The field is present with tinyMCE on but visibility is set to "hidden" by the css.  I rummaged around in the css but I could never find where the visibility for that field was set so that I could just change it directly.  Will look at the error logs to see if I can find out the issue when tinyMCE is enabled.

**Comment by nerdykit** [comment]
How about...  "Failed to load: http://www.xxxxxx.ca/gallery/zp-core/zp-extensions/tinymce/langs/en_US.UTF8.js"

Found this in the web developer console of Firefox (Mac) and no, there are many files in langs directory but there is no en_US.UTF8.js file there.  Will look around and see if I can find that file, put it there and report back.

**Comment by nerdykit** [comment]
Ha!  Just tried to album edit using Safari (which I haven't used on Zenphoto for many months) and the Album Description field flashed by briefly then disappeared.  I suspect that Safari gave me the cached version of that page using earlier version of Zenphoto then updated the page and set field visibility to hidden.

**Comment by nerdykit** [comment]
Safari error console also reports....

http://www.xxxxxxxxx.ca/gallery/zp-core/js/dirtyforms/jquery.dirtyforms.helpers.tinymce.min.js.map
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by sbillard** [comment]
for that last error please insert 
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.dirtyforms/2.0.0/jquery.dirtyforms.min.js.map"></script>
after line 148 in admin-functions.php

See if that fixes the problem. If not try copying the Canadian or British english file from http://archive.tinymce.com/i18n/ and changing its name to en_US.UTF8.js and see if that fixes the problem.

If neither of these work try disabling all plugins but tinymce. You can use the development  pluginEnabler to first remember your current plugin set, then disable all plugins, then enable tinyMCE. THe buttons for this will be on the overview tab in the development section. It that works we will have to figure out what plugin is interfering.

**Comment by nerdykit** [comment]
Not sure if the src in the line to be added should begin with "//  but did it exactly like that.  No change.  Then plugged a dummy version of en_US.UTF8.js in as instructed and viola!  I've got an edit field back for Album Description.  Both changes are now in place.  Time limited so can't check browser console error reports but will do so ASAP and add them here.

**Comment by nerdykit** [comment]
Have checked the logs.... I think it should be http:// to start the load of that module and made the change.  404 Console error goes away then. So then I removed the dummy en_US.UTF8 file to see which change restored the field.  It's the en_US.UTF8 that matters.

The field that now appears seems to have a full tinyMCE toolbar with options to create file etc.  Was that what was there originally?  Is there a more limited tinyMCE toolbar that you wanted with just text formatting options available?  At least we've got the field back.  I think I will remove the extra line in admin-functions because that did not resolve the problem.

**Comment by nerdykit** [comment]
I now realize that the complexity level of the toolbar for tinyMCE is configurable in the plugin dialog so ignore my comments above about the tinyMCE toolbar.

**Comment by sbillard** [comment]
have you tried other toolbar configurations? tinyMCE really should not be requesting that file. So far I have not found a path that does so. What was the original zenphoto configuration?

**Comment by nerdykit** [comment]
I think that the reference comes in tinymce.min.js  I can't find the specific call but my console error logs the missing file as being called by line 4 at character 10082 and while I can't find any occurrence of en_US.UTF8.js if I search, I CAN find two references to the langs directory that probably build that URL call from pieces.  I'm not a php programmer so I can't really help further.

I wonder if it's a tinyMCE config problem.  I also wonder what files were in the langs folder for previous versions of tinyMCE?  Before I added the UTF8 version of en_US, there was no english language file in langs so it would seem to me that tinyMCE defaults to english US and doesn't require an en_US file to be there (with or without the .UTF8 variant).  So maybe somewhere zenphoto is specifying UTF8 and that forces tinyMCE to go looking for a suitable file in langs.

Not sure what you're asking me above  "What was the original zenphoto configuration?"  I have tried and found a good toolbar configuration for this field.  It's now set at Text Editor Configuration   -->  Light and that looks about right.

**Comment by sbillard** [comment]
The reference to the toolbar setting was that possibly the bug was in a particular toolbar configuration. The language file is indeed loaded by the tinyMCE javascript. There is not supposed to be an English language file--the native encodings of the strings are English. But for some reason tinyMCE thinks it needs a specific version of English--en_US.UTF8. That is not supposed to be possible:(

I am developing a theory and possible fix but I have to admit I really have no clue as to the root source of the issue. I will create a version of ZenPhoto20 with this change later today. In the meantime can you look at the HTML for the page and find the JavaScript function call on `tinymce.init`. There will be a 'language" item parameter. If that says en_US.UTF8 then I am probably right on the symptom if not the root cause.

**Comment by sbillard** [comment]
The trial fix is available at https://github.com/sbillard/ZenPhoto20-DEV/

**Comment by nerdykit** [comment]
Will try out your trial fix next but for the meantime, here's the tinymce.init  call and it looks to my inexperienced eye as if the culprit is actually nanospell but you will see the second language parameter reference is the UTF8 one, I don't know enough to correctly parse the code to determine if it's a parameter of the main function or a sub call.

File is attached.
[tinymce.init.txt](https://github.com/ZenPhoto20/ZenPhoto20/files/677868/tinymce.init.txt)

**Comment by nerdykit** [comment]
Yes, if I turn off the nanospell plugin and remove the en_US.UTF8.js file from langs the field is still present.  So that pretty well confirms that nanospell is guilty.  Yup.  Toggled it off and on and off again and the field appears and disappears according to the state of nanospell.

**Comment by sbillard** [comment]
Thanks, this is the piece of information I needed. Still not sure why things work differently on my server, but at least I know what caused the problem. The nanospell language parameter is redundant, and on your install, incorrect. The fix is to simply remove it.
